# Generated by Django 5.2.12 on 2026-03-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_promotion_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='media_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('document', 'Document')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='media_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='emailblast',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='smsblast',
            name='custom_numbers',
            field=models.TextField(blank=True, help_text='Comma-separated phone numbers'),
        ),
        migrations.AlterField(
            model_name='socialplatformconfig',
            name='extra_field',
            field=models.CharField(blank=True, help_text='Page ID / Phone Number / etc.', max_length=200),
        ),
    ]
