# Generated by Django 5.2.12 on 2026-03-20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_media_fields'),
    ]

    operations = [
        # Add new fields to SocialPlatformConfig
        migrations.AddField(
            model_name='socialplatformconfig',
            name='account_name',
            field=models.CharField(blank=True, help_text='Friendly name for this account', max_length=100),
        ),
        migrations.AddField(
            model_name='socialplatformconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialplatformconfig',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Use this account as the default for posting'),
        ),
        # Add account_name to SocialPost
        migrations.AddField(
            model_name='socialpost',
            name='account_name',
            field=models.CharField(blank=True, help_text='Which account was used', max_length=100),
        ),
    ]
