# Generated by Django 5.2.12 on 2026-03-20 14:38

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_update_social_platform_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialplatformconfig',
            options={'ordering': ['-is_primary', 'platform', 'account_name'], 'verbose_name_plural': 'Social Platform Configs'},
        ),
        migrations.AlterField(
            model_name='socialplatformconfig',
            name='account_name',
            field=models.CharField(blank=True, help_text='Friendly name for this account (e.g., "Main Page", "Events Page")', max_length=100),
        ),
        migrations.AlterField(
            model_name='socialplatformconfig',
            name='extra_field',
            field=models.CharField(blank=True, help_text='Page ID / Account ID / URN', max_length=200),
        ),
        migrations.AlterField(
            model_name='socialplatformconfig',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'X (Twitter)'), ('linkedin', 'LinkedIn'), ('threads', 'Threads'), ('tiktok', 'TikTok')], max_length=20),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=core.models.user_profile_image_path)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('website', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
