# Generated by Django 5.2.12 on 2026-03-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='link_url',
            field=models.URLField(blank=True),
        ),
    ]
