# Generated by Django 5.0.4 on 2026-03-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_socialpost_link_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialplatformconfig',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'X (Twitter)'), ('linkedin', 'LinkedIn'), ('threads', 'Threads'), ('pinterest', 'Pinterest')], max_length=20),
        ),
    ]
