# Generated by Django 5.0.4 on 2026-04-07 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_socialplatformconfig_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebinarAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('account_type', models.CharField(choices=[('page', 'Facebook Page'), ('group', 'Facebook Group'), ('profile', 'Personal Profile')], max_length=20)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('page_id', models.CharField(blank=True, help_text='Facebook Page/Group ID', max_length=100)),
                ('access_token', models.TextField(blank=True, help_text='Securely stored access token')),
                ('token_expires', models.DateTimeField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated: personal, business, niche', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('restricted', 'Restricted'), ('error', 'Error'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('followers_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WebinarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('registration_link', models.URLField(blank=True, max_length=500)),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('event_end_date', models.DateTimeField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='webinar_covers/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='WebinarGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('member_count', models.PositiveIntegerField(default=0)),
                ('size_category', models.CharField(choices=[('small', 'Below 10,000'), ('medium', '10,000 - 100,000'), ('large', 'Above 100,000')], db_index=True, max_length=10)),
                ('engagement', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('restricted', 'Restricted'), ('error', 'Error'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=20)),
                ('niche', models.CharField(blank=True, max_length=100)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500)),
                ('last_posted', models.DateTimeField(blank=True, null=True)),
                ('posts_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-member_count'],
            },
        ),
        migrations.CreateModel(
            name='WebinarPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='webinar_posts/')),
                ('link_url', models.URLField(blank=True, max_length=500)),
                ('spin_variations', models.TextField(blank=True, help_text='JSON array of spin variations')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('posting', 'Posting'), ('posted', 'Posted'), ('partial', 'Partially Posted'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('delay_minutes', models.PositiveIntegerField(default=5, help_text='Delay between posts in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.webinarevent')),
                ('target_accounts', models.ManyToManyField(blank=True, related_name='targeted_posts', to='core.webinaraccount')),
                ('target_groups', models.ManyToManyField(blank=True, related_name='targeted_posts', to='core.webinargroup')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebinarPostLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('post_url', models.URLField(blank=True, max_length=500)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('shares_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.webinaraccount')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.webinargroup')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.webinarpost')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='webinargroup',
            index=models.Index(fields=['size_category', 'status'], name='core_webina_size_ca_59e9c8_idx'),
        ),
        migrations.AddIndex(
            model_name='webinargroup',
            index=models.Index(fields=['niche'], name='core_webina_niche_ad2c49_idx'),
        ),
    ]
