# Generated by Django 5.0.4 on 2026-04-07 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_webinaraccount_webinarevent_webinargroup_webinarpost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directorysubmission',
            name='directory',
        ),
        migrations.RemoveField(
            model_name='directorysubmission',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='directorysubmission',
            name='location',
        ),
        migrations.DeleteModel(
            name='Directory',
        ),
        migrations.DeleteModel(
            name='DirectorySubmission',
        ),
    ]
