# Generated by Django 5.0.4 on 2026-04-10 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_directorysubmission_directory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='email_attachments/%Y/%m/')),
                ('blob_name', models.CharField(max_length=255)),
                ('original_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.emailblast')),
            ],
        ),
    ]
